version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
