version: 2.1
orbs:
  node: circleci/node@4.7.0
  codecov: codecov/codecov@1.0.2

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - node/install-packages:
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm
      - run: npm run setup
      - codecov/upload:
          file: "./coverage/clover.xml"
          token: 16bd5590-dfd5-42ac-8b2d-27b1ad52e86e

workflows:
  sample:
    jobs:
      - build-and-test
      # For running simple node tests, you could optionally use the node/test job from the orb to replicate and replace the job above in fewer lines.
      # - node/test
